using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace NetSuiteIntegration.Models
{
    public class NetSuiteCustomer
    {
        public List<NetSuiteCustomerLink>? Links { get; set; }
        public NetSuiteCustomerAddressBook? AddressBook { get; set; }
        public NetSuiteCustomerAlcoholRecipientType? AlcoholRecipientType { get; set; }
        public double? Balance { get; set; }
        public NetSuiteCustomerCreditHoldOverride? CreditHoldOverride { get; set; }
        public NetSuiteCustomerCurrency? Currency { get; set; }
        public NetSuiteCustomerCurrencyList? CurrencyList { get; set; }
        public bool? Custentity2663CustomerRefund { get; set; }
        public bool? Custentity2663DirectDebit { get; set; }
        public string? CustentityEscLastModifiedDate { get; set; }
        public bool? CustentityNawTransNeedApproval { get; set; }
        public string? CustentitySapMfsBpCc { get; set; }
        public string? CustentityclientStudentno { get; set; }
        public string? CustentitysapMflBpCc { get; set; }
        public NetSuiteCustomerCustomForm? CustomForm { get; set; }
        public DateTime? DateCreated { get; set; }
        public string? DefaultAddress { get; set; }
        public double? DepositBalance { get; set; }
        public string? Email { get; set; }
        public NetSuiteCustomerEmailPreference? EmailPreference { get; set; }
        public bool? EmailTransactions { get; set; }
        public string? EntityID { get; set; }
        public NetSuiteCustomerEntityStatus? EntityStatus { get; set; }
        public string? ExternalID { get; set; }
        public bool? FaxTransactions { get; set; }
        public string? FirstName { get; set; }
        public NetSuiteCustomerGlobalSubscriptionStatus? GlobalSubscriptionStatus { get; set; }
        public NetSuiteCustomerGroupPricing? GroupPricing { get; set; }
        [Key]
        public string? ID { get; set; }
        public bool? IsAutogeneratedRepresentingEntity { get; set; }
        public bool? IsBudgetApproved { get; set; }
        public bool? IsInactive { get; set; }
        public bool? IsPerson { get; set; }
        public NetSuiteCustomerItemPricing? ItemPricing { get; set; }
        public NetSuiteCustomerLanguage? Language { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public string? LastName { get; set; }
        public string? MiddleName { get; set; }
        public double? OverdueBalance { get; set; }
        public bool? PrintTransactions { get; set; }
        public NetSuiteCustomerReceivablesAccount? ReceivablesAccount { get; set; }
        public NetSuiteCustomerSalesTeam? SalesTeam { get; set; }
        public bool? ShipComplete { get; set; }
        public NetSuiteCustomerShippingCarrier? ShippingCarrier { get; set; }
        public NetSuiteCustomerSubsidiary? Subsidiary { get; set; }
        public bool? SyncSalesTeams { get; set; }
        public double? UnbilledOrders { get; set; }
        public bool? Unsubscribe { get; set; }
    }
}
